export const Userdata = [
    {
        id: 1,
        personName: "John Doe",
        personImage: "https://i.pravatar.cc/150?img=1",
        personMail: "john.doe@example.com",
        personWorkExperience: "Software Engineer",
        personWorkExperienceDescription: "5 years of experience in developing web applications.",
        personAge: 30,
        personAboutMe: "I am a passionate software engineer with a love for coding and problem-solving.",
    },
    {
        id: 2,
        personName: "Jane Smith",
        personImage: "https://i.pravatar.cc/150?img=2",
        personMail: "jane.smith@example.com",
        personWorkExperience: "Product Manager",
        personWorkExperienceDescription: "3 years of experience in managing product development.",
        personAge: 28,
        personAboutMe: "I enjoy working with cross-functional teams to build amazing products.",
    },
    {
        id: 3,
        personName: "Peter Jones",
        personImage: "https://i.pravatar.cc/150?img=3",
        personMail: "peter.jones@example.com",
        personWorkExperience: "UX Designer",
        personWorkExperienceDescription: "4 years of experience in designing user-friendly interfaces.",
        personAge: 32,
        personAboutMe: "I am a creative UX designer who loves to create beautiful and intuitive designs.",
    },
    {
        id: 4,
        personName: "Mary Johnson",
        personImage: "https://i.pravatar.cc/150?img=4",
        personMail: "mary.johnson@example.com",
        personWorkExperience: "Data Scientist",
        personWorkExperienceDescription: "6 years of experience in analyzing data and building machine learning models.",
        personAge: 35,
        personAboutMe: "I am a data enthusiast who is passionate about finding insights from data.",
    },
    {
        id: 5,
        personName: "David Williams",
        personImage: "https://i.pravatar.cc/150?img=5",
        personMail: "david.williams@example.com",
        personWorkExperience: "Frontend Developer",
        personWorkExperienceDescription: "2 years of experience in building responsive websites.",
        personAge: 25,
        personAboutMe: "I am a frontend developer who loves to create beautiful and interactive user interfaces.",
    },
    {
        id: 6,
        personName: "Sarah Brown",
        personImage: "https://i.pravatar.cc/150?img=6",
        personMail: "sarah.brown@example.com",
        personWorkExperience: "Backend Developer",
        personWorkExperienceDescription: "7 years of experience in building scalable backend systems.",
        personAge: 38,
        personAboutMe: "I am a backend developer who is passionate about building robust and efficient systems.",
    },
    {
        id: 7,
        personName: "Michael Davis",
        personImage: "https://i.pravatar.cc/150?img=7",
        personMail: "michael.davis@example.com",
        personWorkExperience: "Full Stack Developer",
        personWorkExperienceDescription: "8 years of experience in developing end-to-end web applications.",
        personAge: 40,
        personAboutMe: "I am a full stack developer who loves to work on both the frontend and backend.",
    },
    {
        id: 8,
        personName: "Emily Miller",
        personImage: "https://i.pravatar.cc/150?img=8",
        personMail: "emily.miller@example.com",
        personWorkExperience: "Mobile App Developer",
        personWorkExperienceDescription: "3 years of experience in developing native mobile apps.",
        personAge: 27,
        personAboutMe: "I am a mobile app developer who is passionate about creating amazing user experiences on mobile.",
    },
    {
        id: 9,
        personName: "William Wilson",
        personImage: "https://i.pravatar.cc/150?img=9",
        personMail: "william.wilson@example.com",
        personWorkExperience: "DevOps Engineer",
        personWorkExperienceDescription: "5 years of experience in automating infrastructure and deployments.",
        personAge: 33,
        personAboutMe: "I am a DevOps engineer who loves to automate everything.",
    },
    {
        id: 10,
        personName: "Olivia Moore",
        personImage: "https://i.pravatar.cc/150?img=10",
        personMail: "olivia.moore@example.com",
        personWorkExperience: "QA Engineer",
        personWorkExperienceDescription: "4 years of experience in testing software applications.",
        personAge: 29,
        personAboutMe: "I am a QA engineer who is passionate about ensuring software quality.",
    },
    {
        id: 11,
        personName: "James Taylor",
        personImage: "https://i.pravatar.cc/150?img=11",
        personMail: "james.taylor@example.com",
        personWorkExperience: "Scrum Master",
        personWorkExperienceDescription: "6 years of experience in leading agile teams.",
        personAge: 36,
        personAboutMe: "I am a Scrum Master who loves to help teams deliver value to customers.",
    },
    {
        id: 12,
        personName: "Sophia Anderson",
        personImage: "https://i.pravatar.cc/150?img=12",
        personMail: "sophia.anderson@example.com",
        personWorkExperience: "Business Analyst",
        personWorkExperienceDescription: "7 years of experience in gathering and analyzing business requirements.",
        personAge: 39,
        personAboutMe: "I am a business analyst who is passionate about understanding business needs and translating them into technical requirements.",
    },
    {
        id: 13,
        personName: "Benjamin Thomas",
        personImage: "https://i.pravatar.cc/150?img=13",
        personMail: "benjamin.thomas@example.com",
        personWorkExperience: "Project Manager",
        personWorkExperienceDescription: "10 years of experience in managing complex projects.",
        personAge: 45,
        personAboutMe: "I am a project manager who loves to deliver projects on time and within budget.",
    },
    {
        id: 14,
        personName: "Mia Jackson",
        personImage: "https://i.pravatar.cc/150?img=14",
        personMail: "mia.jackson@example.com",
        personWorkExperience: "IT Consultant",
        personWorkExperienceDescription: "12 years of experience in providing IT consulting services.",
        personAge: 50,
        personAboutMe: "I am an IT consultant who helps businesses leverage technology to achieve their goals.",
    },
    {
        id: 15,
        personName: "Ethan White",
        personImage: "https://i.pravatar.cc/150?img=15",
        personMail: "ethan.white@example.com",
        personWorkExperience: "Network Engineer",
        personWorkExperienceDescription: "8 years of experience in designing and managing computer networks.",
        personAge: 42,
        personAboutMe: "I am a network engineer who is passionate about building reliable and secure networks.",
    },
    {
        id: 16,
        personName: "Isabella Harris",
        personImage: "https://i.pravatar.cc/150?img=16",
        personMail: "isabella.harris@example.com",
        personWorkExperience: "Database Administrator",
        personWorkExperienceDescription: "9 years of experience in managing and maintaining databases.",
        personAge: 43,
        personAboutMe: "I am a database administrator who is passionate about ensuring data integrity and availability.",
    },
    {
        id: 17,
        personName: "Alexander Martin",
        personImage: "https://i.pravatar.cc/150?img=17",
        personMail: "alexander.martin@example.com",
        personWorkExperience: "Security Analyst",
        personWorkExperienceDescription: "6 years of experience in protecting computer systems and networks from cyber threats.",
        personAge: 37,
        personAboutMe: "I am a security analyst who is passionate about cybersecurity and protecting digital assets.",
    },
    {
        id: 18,
        personName: "Charlotte Garcia",
        personImage: "https://i.pravatar.cc/150?img=18",
        personMail: "charlotte.garcia@example.com",
        personWorkExperience: "Cloud Engineer",
        personWorkExperienceDescription: "5 years of experience in designing and managing cloud infrastructure.",
        personAge: 34,
        personAboutMe: "I am a cloud engineer who is passionate about cloud computing and building scalable and resilient systems.",
    },
    {
        id: 19,
        personName: "Daniel Martinez",
        personImage: "https://i.pravatar.cc/150?img=19",
        personMail: "daniel.martinez@example.com",
        personWorkExperience: "Machine Learning Engineer",
        personWorkExperienceDescription: "4 years of experience in building and deploying machine learning models.",
        personAge: 31,
        personAboutMe: "I am a machine learning engineer who is passionate about artificial intelligence and building intelligent systems.",
    },
    {
        id: 20,
        personName: "Amelia Robinson",
        personImage: "https://i.pravatar.cc/150?img=20",
        personMail: "amelia.robinson@example.com",
        personWorkExperience: "AI Researcher",
        personWorkExperienceDescription: "3 years of experience in conducting research in the field of artificial intelligence.",
        personAge: 26,
        personAboutMe: "I am an AI researcher who is passionate about pushing the boundaries of artificial intelligence.",
    },
];